apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-node
spec:
  replicas: 5
  selector:
    matchLabels:
      app: hello-node
  template:
    metadata:
      labels:
        app: hello-node
    spec:
      containers:
      - name: hello-node
        image: narendranrammudo/k8s-project-1:0.1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 3000
